// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzDALJvwD14ef0JVNtTDSkPyiLdvCEG8',
    appId: '1:181833965292:web:ed997aa01225b0f0a48fc9',
    messagingSenderId: '181833965292',
    projectId: 'campustrace-503f6',
    authDomain: 'campustrace-503f6.firebaseapp.com',
    storageBucket: 'campustrace-503f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4eDftGN2xbIQ776RZFhehDAndfokTRE',
    appId: '1:181833965292:android:cc4c9fa0b8af0a82a48fc9',
    messagingSenderId: '181833965292',
    projectId: 'campustrace-503f6',
    storageBucket: 'campustrace-503f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANCpEPAggUfsattZ8VdeTEY4EjmW3NnX4',
    appId: '1:181833965292:ios:37a74bd5bb3620fda48fc9',
    messagingSenderId: '181833965292',
    projectId: 'campustrace-503f6',
    storageBucket: 'campustrace-503f6.firebasestorage.app',
    iosBundleId: 'com.example.campusTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANCpEPAggUfsattZ8VdeTEY4EjmW3NnX4',
    appId: '1:181833965292:ios:37a74bd5bb3620fda48fc9',
    messagingSenderId: '181833965292',
    projectId: 'campustrace-503f6',
    storageBucket: 'campustrace-503f6.firebasestorage.app',
    iosBundleId: 'com.example.campusTrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFzDALJvwD14ef0JVNtTDSkPyiLdvCEG8',
    appId: '1:181833965292:web:bfdc0eab212d2d92a48fc9',
    messagingSenderId: '181833965292',
    projectId: 'campustrace-503f6',
    authDomain: 'campustrace-503f6.firebaseapp.com',
    storageBucket: 'campustrace-503f6.firebasestorage.app',
  );
}
